### PR TITLE
[welcome] Show welcome-image when all requirements are satisfied

### LINKED ISSUE #1974: Calamares 3.3 - Welcome page does not load image
**Describe the bug**
Open Calamares 3.3 welcome module does not show image anymore.

**To Reproduce**
1. Start Calamares 3.3 with the default settings.conf (no other changes made).
2. Welcome page loads languages but not the image

**Expected behavior**
Show the configured image in the welcome module.

**Screenshots and Logs**
calamares_welcome_3 3

I found this in the log:
```
2022-06-04 - 13:51:01 [2]: void Calamares::QmlViewStep::showFailedQml()
    WARNING: QmlViewStep "welcomeq@welcomeq" loading failed. 
2022-06-04 - 13:51:01 [6]:     .. QML error: "qrc:/welcomeq.qml:17 module \"QtGraphicalEffects\" is not installed\nqrc:/welcomeq.qml:16 module \"org.kde.kirigami\" is not installed\nqrc:/welcomeq.qml:15 module \"QtQuick.Layouts\" is not installed\nqrc:/welcomeq.qml:14 module \"QtQuick.Controls\" is not installed\nqrc:/welcomeq.qml:17 module \"QtGraphicalEffects\" is not installed\nqrc:/welcomeq.qml:16 module \"org.kde.kirigami\" is not installed\nqrc:/welcomeq.qml:15 module \"QtQuick.Layouts\" is not installed\nqrc:/welcomeq.qml:14 module \"QtQuick.Controls\" is not installed\nqrc:/welcomeq.qml:17 module \"QtGraphicalEffects\" is not installed\nqrc:/welcomeq.qml:16 module \"org.kde.kirigami\" is not installed\nqrc:/welcomeq.qml:15 module \"QtQuick.Layouts\" is not installed\nqrc:/welcomeq.qml:14 module \"QtQuick.Controls\" is not installed\nqrc:/welcomeq.qml:17 module \"QtGraphicalEffects\" is not installed\nqrc:/welcomeq.qml:16 module \"org.kde.kirigami\" is not installed\nqrc:/welcomeq.qml:15 module \"QtQuick.Layouts\" is not installed\nqrc:/welcomeq.qml:14 module \"QtQuick.Controls\" is not installed\n" 

```

After installing qml-module-org-kde-kirigami2 (pulls in qml-module-qtgraphicaleffects,  qml-module-qtquick-layouts, qml-module-qtquick-controls) the above mentioned warning was gone, but the welcome module still did not load the image.

Log after apt install:
[session.log](https://github.com/calamares/calamares/files/8838050/session.log)

### PR DESCRIPTION
**Pull request by adriaandegroot**
There was a missing call to update the requirements-list widget when the requirements are done checking. While here, stop the countdown when we know the requirements are not going to be checked again.

FIXES #1974

### CODE REVIEW

**Comment by demmm** [comment]
Unfortunately, doesn't fix for me, builds, runs, but still stuck with the counting spinner & no welcome image (welcomeq is still fine, checker widget works for both, if for example, no internet, both show the warning, but the welcome module still shows the spinner then too).
I can't find anything in the log why, no entries for checkerWidget or checkingWidget.  Seems to hang here https://github.com/calamares/calamares/blob/calamares/src/modules/welcome/WelcomePage.cpp#L187
But not clear where that all connects.

**Comment by abalfoort** [comment]
The verdict() method just returns a boolean. I checked and all seems as expected. I still can't find what's actually wrong with this module. If I have the time I'll compare the 3.2 module with the current one.

**Comment by adriaandegroot** [comment]
`verdict()` has nothing to do with this. That function is used to report the last are-all-requirements-met result, and only to enable / disable the *next* button. The widget code is all in `ResultsListWidget`.

**Comment by demmm** [comment]
Ready to merge, issue 1974 fixed

**Pull request merged**
