### PR TITLE
better looks and logo size

### PR DESCRIPTION
**Pull request by blackPantherOS**
We use these sizes in blackPanther OS, I think this is a better looks

### CODE REVIEW

**Comment by adriaandegroot** [comment]
I don't think we should start pushing and pulling on the window sizes from within C++ code; what looks better for you looks worse for others, depending on default themes, fonts, etc. It will also break a bunch of automated downstream tests that use openQA to check for rendering defects, for instance.

I would accept a PR that moves this into a configuration file -- e.g. `branding.conf`, either a new top-level key *window* or under *style*, setting minw, minh, sidebarproportion.

**Comment by bill-auger** [comment]
i will add that this image entity 'Branding::ProductIcon' is currently the same that is used for the WM/DE icon which is always square and also much smaller - the consensus is that the original intention was for this sidebar image to use the 'Branding::ProductLogo' entity - note that it is rendered inside of a 'logoLabel' inside of a 'logoLayout' - see PR #826 

if this PR is accepted as is, then the intended input for 'Branding::ProductIcon' would presumably be rectangular which would make the WM/DE icon to be distorted

it has been suggewsted on IRC that perhaps a new entry be added to branding.desc and a new entity in Branding.cpp such as: 'ProductLogoWide' for an explicitly rectangular input image and allow this feature to be a configuration optoin as suggested to switch between using the 'ProductLogo' (square) and the 'ProductLogoWide' (rectangular) sources

**Comment by adriaandegroot** [comment]
Closing this one because of no response to the request for changes; it may also be superceded by @raurodse  and the CSS-styling changes he is proposing.

**Comment by bill-auger** [comment]
i presume that is PR #961 - i am still interested in this because i have been carrying a patch for this - i will subscribe to #961

**Pull request closed without merging**
