### PR TITLE
Set boot flag

### PR DESCRIPTION
**Pull request by aliveafter1000**
https://github.com/calamares/calamares/issues/1046

### CODE REVIEW

**Comment by philmmanjaro** [comment]
This PR lacks backward compatibility to older kpmcore libraries.

**Comment by aliveafter1000** [comment]
?

All I added was:
```

    if( isEfi )
    {
        core->createPartition( dev, rootPartition );
    }
    else
    {
        // Some buggy BIOSes test if the bootflag of at least one partition is set. Otherwise they ignore the device in boot-order. 
        core->createPartition( dev, rootPartition, PartitionTable::FlagBoot );
    }
```

**Comment by philmmanjaro** [comment]
Exactly, which won't work for the older version of kpmcore. Please see also this [comment] (https://github.com/calamares/calamares/issues/1046#issuecomment-436274899) in that regard. Also check the code on how to detect which version of kpmcore is used and adopt accordingly.

**Comment by philmmanjaro** [comment]
@aliveafter1000: can you base your code on the current released [v3.3.0](https://github.com/KDE/kpmcore/blob/3f562ab0f04ff2cc3d1e7ab3707919557650bec8/src/core/partitiontable.h#L71)? There we still have **FlagEsp**.

**Comment by aliveafter1000** [comment]
I told you man. The code is fine. Read the code! 
Read the whole code. You are not understanding it.

**Comment by philmmanjaro** [comment]
@aliveafter1000: please read https://github.com/calamares/calamares/issues/1046#issuecomment-436274899 and check the current released code of [v3.3.0](https://github.com/KDE/kpmcore/blob/3f562ab0f04ff2cc3d1e7ab3707919557650bec8/src/core/partitiontable.h#L71) which is the current version of **CAL** is designed for. There we still have `FlagEsp = 131072`. It got only depreciated in the **master** branch, which is not used by any distribution yet. Not even on Manjaro.

**Comment by philmmanjaro** [comment]
OK, so basically some like [this](https://gitlab.manjaro.org/applications/calamares/commit/af3ffa8) ...

**Comment by aliveafter1000** [comment]
Correct. Yes.

**Comment by adriaandegroot** [comment]
This is in-progress in the fix-partitioning branch.

**Pull request closed without merging**
