### PR TITLE
Update calamares_zh_CN.ts

### PR DESCRIPTION
**Pull request by nekrozis**
Corrected zh_CN typo

### CODE REVIEW

**Comment by demmm** [comment]
Normally, Calamares uses transifex for translations:
https://github.com/calamares/calamares/wiki/Translate-Guide

So, if possible, it would be better to work there though it might be (as an exception), this PR will be merged.

**Comment by nekrozis** [comment]
OK, I will fix it there and close this PR

**Comment by nekrozis** [comment]
I found it a bit of a hindrance to register an account on the site, as it requires a business email address to do so.

**Comment by adriaandegroot** [comment]
I have merged and also applied the change in Transifex. I see a couple more reasons to start moving away from Transifex, so I think we should soon change the documentation to name something else as preferred place for translations.

**Pull request merged**
