### PR TITLE
Add man page

### PR DESCRIPTION
**Pull request by highvoltage**
Add a man page for calamares.

### CODE REVIEW

**Comment by shainer** [comment]
Nice. Why don't you also install it in the correct path? :)

**Comment by teo** [comment]
@highvoltage what @shainer said, this should be installed in the right path by adding the relevant operation to CMake.

**Comment by teo** [comment]
@highvoltage any news on this?

**Comment by adriaandegroot** [comment]
No worries, the CMake stuff is trivial. I am going to move the man page to section 8, though, since it's not a regular user executable command.

**Pull request merged**
