### PR TITLE
[packages] add pamac support

### PR DESCRIPTION
**Pull request by codesardine**

### CODE REVIEW

**Comment by adriaandegroot** [comment]
The `check_db_lock()` function is a bit weird:
 - The `os.exists()` check checks for the file's existence relative to the **host** system, and then runs `rm` in the **target* system. That's not going to help if the root filesystems don't overlap.
 - Why not just `rm -f` the lock file (in the target system)? Then you don't get a failure if the file doesn't exist.

**Comment by adriaandegroot** [comment]
I should add: looks good overall, seems like a sensible addition. You should definitely address the issues above,  and it would be nice if you also:

- added pamac to the list of supported package managers in the example configuration file
- added pamac to the list of supported package managers in the schema file (you'll need to rebase for that, since the schema is being updated to actually work)

**Comment by codesardine** [comment]
I have updated let me know if I miss something.

**Comment by adriaandegroot** [comment]
Merged, thanks! This will be in 3.2.27 which is scheduled for this week.

**Pull request merged**
