### PR TITLE
Add i18n support for percent value

### LINKED ISSUE #2124: Percent value is not localised
During the installing part, the progress bar percentage value shows in the following format: 10%. This is what most locales use, but in some other languages, including Turkish for instance, the sign precedes the number; e.g. %10. The percentage text value should be explicitly made available for translation.

Ekran Resmi 2023-04-09 13 27 57

### PR DESCRIPTION
**Pull request by bitigchi**
Fixes #2124.

### CODE REVIEW

**Comment by bitigchi** [comment]
Thanks for accepting. I'd like to fix this within the translation as well, when would it be available through Transifex?

**Comment by adriaandegroot** [comment]
I added some disambiguation, since the string `%p%` is otherwise kind of obscure. This is in the 3.3 branch, which is not pushed to translations at all, yet. I probably should wrap up the 3.2 series with a final translations release and then switch 3.3 onto the translations.

**Comment by adriaandegroot** [comment]
https://app.transifex.com/calamares/calamares/translate/#tr_TR/calamares/456289361?q=text%3A%25p .. now you can translate it for Turkish!

**Comment by bitigchi** [comment]
Done, thanks!

**Comment by bitigchi** [comment]
@adriaandegroot, currently I am trying to sync Calamares' terminology with KDE; however I am unable to modify some strings, since they were approved before. Is it possible to get full rights for Turkish translations? I am the current KDE language coordinator for Turkish, please let me know if you'd need additional information from my side.

**Comment by adriaandegroot** [comment]
@bitigchi I have bumped you up to coordinator.

**Comment by bitigchi** [comment]
Thank you!

**Pull request merged**
