### PR TITLE
[i18n] esperanto translations

### PR DESCRIPTION
**Pull request by bill-auger**

### CODE REVIEW

**Comment by kkofler** [comment]
I thought translations have to go through Transifex, don't they?

**Comment by bill-auger** [comment]
ive sent them as a patch once before - ade tried it last time and
noticed that it is equivalent

**Comment by adriaandegroot** [comment]
The preferred approach is through Transifex, indeed -- that means that translators can work together and updates are reviewed. Patches **also** work, though:

 - merge patch to Calamares via GH
 - git pull on development machine
 - log in to Transifex
 - Resources -> (pick the resource that was updated in the merge) -> pick language -> *upload translations*
 - Pick the newly-patched .ts file and click ok

It's more work for me, along the lines of "two minutes of button clicking", but that's fine as long as not all of the translations start doing that. Esperanto is special, anyway.

**Comment by bill-auger** [comment]
pk, i was under the crazy presumption that the translation
service had git integration, and that direct commits into the
master repo would actually save you some effort - i will use the
web thing in the future

**Pull request merged**
