### PR TITLE
Add Hebrew and Arabic to the non-ASCII layouts list

### PR DESCRIPTION
**Pull request by ghost**
Adds Hebrew and Arabic to the non-ASCII layouts list.
Please note that I do not know "vconsole-keymap".

P.S. How to add the alternative layouts?
––––––
Related: #1730

### CODE REVIEW

**Comment by LordTermor** [comment]
> P.S. How to add the alternative layouts?

What do you mean exactly? Alternative layout for a source layout or an additional one?

**Comment by ghost** [comment]
> > P.S. How to add the alternative layouts?
> 
> What do you mean exactly? Alternative layout for a source layout or an additional one?

I mean an alternative layout for a source one.

**Comment by LordTermor** [comment]
> > > P.S. How to add the alternative layouts?
> > 
> > 
> > What do you mean exactly? Alternative layout for a source layout or an additional one?
> 
> I mean an alternative layout for a source one.

I doubt it's possible right now but should be easy to change. For now it's being applied to all source layout variants. I'm not aware of all usecases of such feature (working with locales are always like that) so I haven't implemented it. Can you describe your  usecase more so I and other developers can understand how it should be done?

**Comment by ghost** [comment]
> > > > P.S. How to add the alternative layouts?
> > > 
> > > 
> > > What do you mean exactly? Alternative layout for a source layout or an additional one?
> > 
> > 
> > I mean an alternative layout for a source one.
> 
> I doubt it's possible right now but should be easy to change. For now it's being applied to all source layout variants. I'm not aware of all usecases of such feature (working with locales are always like that) so I haven't implemented it. Can you describe your usecase more so I and other developers can understand how it should be done?

Yes, thank you. There is a main standard keyboard layout, and there are alternative layouts (like Hebrew lyx or bibical Hebrew, Arabic QWERTY or Arabic Macintosh). Are the alternative keyboard layouts already added, or need to be added (and how)?

**Comment by LordTermor** [comment]
>  alternative layouts (like Hebrew lyx or bibical Hebrew, Arabic QWERTY or Arabic Macintosh)

It's called "variants" in given terminology. Yes, they're all affected as long as layout is the same (like `ar`).

**Comment by ghost** [comment]
> > alternative layouts (like Hebrew lyx or bibical Hebrew, Arabic QWERTY or Arabic Macintosh)
> 
> It's called "variants" in given terminology. Yes, they're all affected as long as layout is the same (like `ar`).

OK, thank you.

**Comment by adriaandegroot** [comment]
The vconsole settings are for the text console; I really don't know if that's a sensible place to be typing Arabic or Hebrew. What might be indicative is installing Debian stable in text mode, and seeing what that does with Arabic or Hebrew layouts.

Anyway, I've merged this, thank you!

**Pull request merged**
