### PR TITLE
[keyboardq] fix build

### PR DESCRIPTION
**Pull request by demmm**

### CODE REVIEW

**Comment by adriaandegroot** [comment]
This looks a bit half-baked, there's a missing call to set up the Config and there's still a superfluous context object in there -- that's not your fault though, this is still repairing the borked merge of the Config object. I'll take this branch and carry it further.

**Comment by demmm** [comment]
Just an FYI, build will fail without this PR, so I take CI is setup not to build the keyboardq module?

**Comment by adriaandegroot** [comment]
> Just an FYI, build will fail without this PR, so I take CI is setup not to build the keyboardq module?

What's the actual build failure though? Because it builds the module in CI, and locally, and introducing the `class Config` declaration in *KeyboardQmlViewStep.h* is superfluous since *Config.h* is already included.

**Comment by demmm** [comment]
Build fail why this PR was done:
```
Scanning dependencies of target calamares_viewmodule_keyboardq
[ 44%] Building CXX object src/modules/keyboardq/CMakeFiles/calamares_viewmodule_keyboardq.dir/calamares_viewmodule_keyboardq_autogen/mocs_compilation.cpp.o
[ 45%] Building CXX object src/modules/keyboardq/CMakeFiles/calamares_viewmodule_keyboardq.dir/KeyboardQmlViewStep.cpp.o
/home/anke/dev/kcp/calamares/src/calamares/src/modules/keyboardq/KeyboardQmlViewStep.cpp: In member function ‘virtual void KeyboardQmlViewStep::onLeave()’:
/home/anke/dev/kcp/calamares/src/calamares/src/modules/keyboardq/KeyboardQmlViewStep.cpp:82:105: error: no matching function for call to ‘Config::createJobs(QString&, QString&, bool&)’
   82 |     m_jobs = m_config->createJobs( m_xOrgConfFileName, m_convertedKeymapPath, m_writeEtcDefaultKeyboard );
      |                                                                                                         ^
In file included from /home/anke/dev/kcp/calamares/src/calamares/src/modules/keyboardq/KeyboardQmlViewStep.h:14,
                 from /home/anke/dev/kcp/calamares/src/calamares/src/modules/keyboardq/KeyboardQmlViewStep.cpp:11:
/home/anke/dev/kcp/calamares/src/calamares/src/modules/keyboardq/../keyboard/Config.h:36:24: note: candidate: ‘Calamares::JobList Config::createJobs()’
   36 |     Calamares::JobList createJobs();
      |                        ^~~~~~~~~~
/home/anke/dev/kcp/calamares/src/calamares/src/modules/keyboardq/../keyboard/Config.h:36:24: note:   candidate expects 0 arguments, 3 provided
make[2]: *** [src/modules/keyboardq/CMakeFiles/calamares_viewmodule_keyboardq.dir/build.make:104: src/modules/keyboardq/CMakeFiles/calamares_viewmodule_keyboardq.dir/KeyboardQmlViewStep.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2548: src/modules/keyboardq/CMakeFiles/calamares_viewmodule_keyboardq.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Pull request merged**
