### PR TITLE
[packagechooserq] start using prettyName

### PR DESCRIPTION
**Pull request by demmm**
this way it can be used for more instances

### CODE REVIEW

**Comment by demmm** [comment]
Image showing the use of prettyName, 2 packagechooserq instances, packages & bootloader:
Screenshot_20210913_204517

**Comment by adriaandegroot** [comment]
There is a `CalamaresUtils::Locale::TranslatedString` for this purpose; because the *prettyName* is human-readable, it should be translatable (e.g. "Bootloader" is fine in English, but it should *cough* be "Laarslader" in Dutch) so that it follows settings when the language is selected in the Welcome page.

See e.g. the *netinstall* module, where the Config object loads the sidebar label and top-text from the configuration file, and it is translated too. The *packagechooser* module does something similar. That should just move to the Config object, rather than living in the ViewStep; then it's shared between both versions, and they can both use the *labels* key to set sub-key *step* (and *step[nl]*) with relevant strings.

**Comment by adriaandegroot** [comment]
.. so, while this specific code is OK, it could be better -- more flexible, resilient for translations -- both for this module and *packagechooser*.

**Comment by demmm** [comment]
Best to close this one then, and get it (at whatever convenient time) from packagechooser.

**Comment by demmm** [comment]
No need to move it to config in packagechooser, I have the translation working locally, and no-one else uses packagechoosrq, let alone extra instances, there is no need for prettyName in main Calamares.

**Pull request closed without merging**
