### PR TITLE
[partition] Strip extra file after the at sign

### PR DESCRIPTION
**Pull request by gportay**
- os-proper may return an extra file after the device:
  /dev/sda1:Ubuntu 19.10 (19.10):Ubuntu:linux
  /dev/sdb1@/EFI/Microsoft/Boot/bootmgfw.efi:Windows Boot Manager:Windows:efi

### CODE REVIEW

**Comment by gportay** [comment]
I am not sure about the second part of the patch because we lose some information.

``` diff
             osproberEntries.append(
                 { prettyName, path, QString(), canBeResized( core, path ), lineColumns, fstabEntries, homePath } );
-            osproberCleanLines.append( line );
+            osproberCleanLines.append( lineColumns.join( ':' ) );
         }
     }
```
We lost the part `/EFI/Microsoft/Boot/bootmgfw.efi:Windows Boot Manager:Windows:efi` in the example below:

```
/dev/sda1:Ubuntu 19.10 (19.10):Ubuntu:linux
/dev/sdb1@/EFI/Microsoft/Boot/bootmgfw.efi:Windows Boot Manager:Windows:efi
```
Maybe, the users of the global storage `osproberLines` should strip it themself before using it.

@adriaandegroot, any though?

**Comment by adriaandegroot** [comment]
I wonder why the replace widget is using the (unstructured) os-prober lines, rather than the structured data that has been collected from them? Possibly we should put the @-part into the OspropberEntries -- it **looks** like they're related to the EFI-boot-executable that is used for them, so worth saving.

I'd prefer something to get rid of the big stringlist, overall. Are there any other users of that stringlist than replacewidget?

**Comment by adriaandegroot** [comment]
@gportay is this still in the RFC stage? Functionally it seems sound to me (you have systems that return this kind of data, so you can tell me if consumers of the os-prober data are affected better than I can).

**Comment by gportay** [comment]
I would say it is not an RFC anymore.

Do you know an existing use case? I made the change to suppress a warning iirc. If not, I can test it test and tells the changes.

I do not have the time to test it right now as I am on holiday. Let me have a look at it on September.

**Comment by gportay** [comment]
Rebased on `calamares/calamares`.

**Comment by gportay** [comment]
Fixed indentation violations.

**Pull request merged**
