### PR TITLE
implement https://calamares.io/bugs/browse/CAL-341

### PR DESCRIPTION
**Pull request by demmm**
Let me know if it is an issue this work was done in the choicepreview branch, it is what I'm working in and using.  If it is then will remove this fork and redo in master.
This change is tested to build and work in the GUI.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Hmm, I quite don't know why the user has to have a checkbox then? What happens if he has it unchecked?

**Comment by demmm** [comment]
@teo 
Even if this pull request is acceptable as is now, please do not merge.
I do see a flaw how it is setup in current git master/choicepreview.
When the default setting is used, use same password for user and root, then when the user unchecks the setting, user can still continue (next is enabled) without entering a matching root password.
I will work on setting next as disabled in that case, and will have that toggle carry over to the option of starting with not re-using password.
So imo, "next" should be disabled anytime the root password box is shown, "next" should be enabled anytime it is not.

**Comment by philmmanjaro** [comment]
Would it not been better to check if the **passwords** match before enabling **Next**? Anyway, good catch in that regard.

**Comment by demmm** [comment]
Nothing to do with password matching, as soon as you start typing the root password check section of userpage.cpp kicks in, and next is disabled.
The issue is as explained in https://calamares.io/bugs/browse/CAL-344

**Comment by philmmanjaro** [comment]
Ok, now I got it. Point taken. Blank **root** passwords would be **Windows** then ;)

**Comment by demmm** [comment]
@teo 
Name change implemented, no luck in fixing bug https://calamares.io/bugs/browse/CAL-344
Probably best to have that in a different pull request/commit anyway.
Can be merged now, if useful for Calamares.

**Pull request merged**
