### PR TITLE
[WIP] Pick timezone from /etc/timezone #1517

### PR DESCRIPTION
**Pull request by tm9k1**

### CODE REVIEW

**Comment by tm9k1** [comment]
I'm thinking
```
bool success = false;
if ( hasInternetConnection )
    success = getTzFromGeoIP(); 
if ( !success && hasEtcTimezone ) 
    success =getTzFromFile(); 
if ( !success ) 
    getTzFromFixedVals();
if ( !success ) 
    success = getTzFromQtDefault(); 
```

**Comment by adriaandegroot** [comment]
The plan I had -- which you don't necessarily have to follow! -- is more along the lines of:
- in `locale.conf`, introduce a key *defaultTimezoneSource*, put it near the top of the file for documentation purposes, since it's going to determine which of the following keys are going to be used; this key can have four values:
  - *fixed*, to use the region/zone set explicitly in the file
  - *system*, to use whatever the system's TZ is (from Qt)
  - *etc-timezone*, to use the contents of that file
  - *geoip*, to do GeoIP lookup

The key *usesystemTimezone* should be marked deprecated; if no source is explicitly set, but *usesystemtimezone* is, then behave as if *system* was specified. There's probably more cases to handle for figuring out which source to use. I like your idea of fallbacks: there's no sense in **failing** to set a TZ if a specific source is mentioned, and it doesn't work but there is other deta available.

**Comment by adriaandegroot** [comment]
Unfortunately, it turns out that *useSystemTimezone* already does all the things we would need to support this, on the systems that usefully support the file. So I'm going to close this as "not needed". Sorry about that, @taskmaster9001

**Comment by tm9k1** [comment]
no worries, @adriaandegroot . I'll try to find something else!

**Pull request closed without merging**
