### PR TITLE
[bootloader] Fix error with systemd-boot when path exists in the ESP

### LINKED ISSUE #1840: Calamares fails when installing over an existing installation, while using systemd-boot and reusing the ESP
**Describe the bug**
The bootloader module encounters an error when installing, if you have previously installed the same distribution using the same ESP, and are using systemd-boot.

**To Reproduce**
1. Configure Calamares to use systemd-boot.
2. Install to an EFI machine.
3. After installation finishes, reboot back into the live environment and try to install again.
4. Partition in any way, as long as the ESP is kept and reused (as is typical when dual-booting with Windows, for instance).

**Expected behavior**
Calamares should overwrite existing bootloader files, or at least ask the user about it, instead of completely failing.

**Screenshots and Logs**
Screenshot of the error that appears: https://i.imgur.com/YJwJJbk.png

**Additional context**
Currently, the only way to work around this is to either delete your ESP (breaking Windows in a dual-boot setup) or to open the partition and delete your distribution's files manually.

### PR DESCRIPTION
**Pull request by dalto8**
Fixes https://github.com/calamares/calamares/issues/1840

### CODE REVIEW

**Comment by hphilm** [comment]
LGTM

**Comment by demmm** [comment]
Overwriting without warning? Not a good idea imo, better make the file name unique by adding a date stamp or something similar.

**Comment by dalto8** [comment]
> Overwriting without warning? Not a good idea imo, better make the file name unique by adding a date stamp or something similar.

That would create a mess the way this is currently written.  I think the case where this would overwrite something important is an edge case.  It would require both the entry name and the kernel names to match.

Honestly, what it is doing here is pretty strange to being with.  This is really just a band-aid until 3.3 where this has already been addressed.

That being said, it wouldn't be hard to create unique directory names, I am just not confident that is really the right thing.  If there is a consensus that it would be a better approach, I can make that change.

**Comment by demmm** [comment]
Just checked more, I see now it is adjusting the kernel image location, not the conf files (not clear from the bug report this addresses if the error is related to the kernel image, but seems so). This means, ignore my previous comment.

**Comment by adriaandegroot** [comment]
`ok.mkdir()` is not documented to have an `exist_ok` named parameter. That is an `os.makedirs()` thing.

**Comment by adriaandegroot** [comment]
Uniqueing of the name is something requested in #1820 , and there's a branch to playfully do that.

**Comment by adriaandegroot** [comment]
I fixed this up and cherry-picked to the *calamares* branch.

**Pull request closed without merging**
