### PR TITLE
[networkcfg] add setting the correct target user in copied file

### PR DESCRIPTION
**Pull request by demmm**
see https://github.com/calamares/calamares/issues/1754

### CODE REVIEW

**Comment by hphilm** [comment]
We also could check for the `permissions` line in the files and replace it regardless, however this seems to work also.

**Comment by demmm** [comment]
AFAIK, `permissions` is always there, plus it shouldn't be replaced, patch only works if the live user is listed in the file, thus that one needs replacing.
But I'm redoing an ISO (plan was to release today, but will postpone now with this possible fix in place), so lots of different options will be tested.

**Comment by hphilm** [comment]
All good. keep us updated.

**Comment by demmm** [comment]
Doesn't work as is, no crashes or install fail, but live user is not detected right, will need a different option for `live_user = getpass.getuser()`.  That one returns `root` when Cala runs.

**Comment by saber716rus** [comment]
When will it be implemented? I saw only "FS label" in manjar, but not the mount option.

**Comment by demmm** [comment]
What does mount option have to do with network settings being preserved on the target system?  Looks llke you commented on a wrong ticket.

**Comment by saber716rus** [comment]
So you yourself tied this comit to my topic.

**Pull request merged**
