### PR TITLE
improved btrfs support

### PR DESCRIPTION
**Pull request by ghost**
although it is hardcoded but it is better than current implementation in calamares.

### CODE REVIEW

**Comment by adriaandegroot** [comment]
Yeah, all those hardcoded blocks and code repetition show that this needs a proper configuration and code, but it's good to have a collection of "this is what we would want it to look like" since that can steer the design of that configuration.

I'll leave the PR open and close it once something similar has landed.

**Comment by adriaandegroot** [comment]
This bears directly also on #1375 (and has the same kind of issues -- expanding hardcoded lists, rather than introducing configuration and a bit of software architecture)

**Comment by Chrysostomus** [comment]
Tried using this on an installation but, either I misconfigured it or there is something wrong with the patch. It only configured the root subvolume and nothing else. Testing further...

**Comment by ghost** [comment]
https://gitlab.com/garuda-linux/tools/iso-profiles/-/tree/master/shared/garuda/live-overlay/usr/lib/calamares/modules



Here all the modified modules that i use in garuda linux

**Comment by adriaandegroot** [comment]
@librewish thanks for the PR. As you can see I've merged @Chrysostomus 's version because that is configurable from the config file(s) rather than being hard-coded. I hope that's an improvement that is compatible with your work at Garuda Linux -- could you try to follow the config for the mount- and fstab modules as it is now, to replace your hard-coded setup?

If so, then you can simplify to a config-file rather than patches, and we're all better (and if not, file issues and Matti can fix them).

**Comment by adriaandegroot** [comment]
Closing as "implemented in other way"

**Pull request closed without merging**
