### PR TITLE
Update license shields

### PR DESCRIPTION
**Pull request by wiz64**
Will change :
image
To:
image

### CODE REVIEW

**Comment by dalto8** [comment]
Is that the right thing to do since different licenses applies to individual files in Calamares?

**Comment by wiz64** [comment]
> ng to do since different licenses applies to individual file

took reference from :
https://en.wikipedia.org/wiki/Calamares_(software)

**Comment by wiz64** [comment]
> Is that the right thing to do since different licenses applies to individual files in Calamares?

took reference from : https://en.wikipedia.org/wiki/Calamares_(software)
(and also the previous button points to GPL)

**Comment by demmm** [comment]
IMO, either use this PR, or remove the license icon entirely.  As stated, icon has always linked to GPL, so might as well use it.  Having it as unspecified makes no sense at all.

**Comment by wiz64** [comment]
> IMO, either use this PR, or remove the license icon entirely. As stated, icon has always linked to GPL, so might as well use it. Having it as unspecified makes no sense at all.

or we can put it to "Multiple", but GPL makes sense

**Comment by demmm** [comment]
If you want to put multiple, then also adjust the link, make it go to the license directory https://github.com/calamares/calamares/tree/calamares/LICENSES

**Comment by wiz64** [comment]
> If you want to put multiple, then also adjust the link, make it go to the license directory https://github.com/calamares/calamares/tree/calamares/LICENSES

Updated to Multiple
image
I would opt for GPL ... Multiple is also okay

**Pull request merged**
