### PR TITLE
Fix reported partition size.

### PR DESCRIPTION
**Pull request by stikonas**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@stikonas: already fixed in **master** or why does it only be needed in our **stable** branch?

**Comment by kkofler** [comment]
The idea is that it will be upmerged to `master` from the stable branch in the regular upmerges. This (commit to the lowest branch and upmerge the branches) is the common KDE git workflow. (And yes, this differs from how distros usually work.)

**Comment by adriaandegroot** [comment]
What @kkofler said: if it's a bug fix which applies to a stable branch, I would rather have it fixed in stable and merged to master than have it fixed in two separate commits.

**Comment by philmmanjaro** [comment]
@adriaandegroot: ya, makes totally sense.

**Pull request merged**
