### PR TITLE
Set boot flag & CAL may delete partitions during disk-probe

### PR DESCRIPTION
**Pull request by aliveafter1000**
Set boot flag
https://github.com/calamares/calamares/issues/1046

CAL may delete partitions during disk-probe
https://github.com/calamares/calamares/issues/1044

### CODE REVIEW

**Comment by kkofler** [comment]
You should file separate pull requests for separate fixes. It is generally a good idea to not pull request from your fork's master, but to create a separate work branch in your fork for each pull request.

**Comment by aliveafter1000** [comment]
Yeah, I was thoroughly confused (new at this). Oh, well.

**Comment by philmmanjaro** [comment]
@aliveafter1000, do you need help with this? From the review of both patches it might work, however had no time yet to test it. Was it tested from your end?

**Comment by aliveafter1000** [comment]
oops. one small mistake.

Need to check if !isEfi before setting the boot flag to root partition otherwise we now have a EFI partition marked as bootable and a root partition marked as bootable.

**Pull request closed without merging**
