### PR TITLE
Use graphical decryption prompt with plymouth

### PR DESCRIPTION
**Pull request by Chrysostomus**

### CODE REVIEW

**Comment by kkofler** [comment]
That is not going to be of any use in practice though, because Calamares uses full disk encryption including `/boot` and hence sets up the system to already prompt for the passphrase in GRUB. Everything else is then unlocked with a keyfile stored in the encrypted `/boot` partition.

Any setup where you would get a decryption prompt from Plymouth is **not** supported by Calamares, see #1311.

**Comment by Chrysostomus** [comment]
Aaah, that's why it wasn't implement yet. Thank you for clarification! 😊

**Comment by hphilm** [comment]
We will have the extra hook now, but it won't be used in that case anyway. Only grub will prompt for the password

**Comment by Chrysostomus** [comment]
But if someone uses manual partitioning, they can still benefit.

**Comment by kkofler** [comment]
No, because Calamares will **not** set up a working and secure system if you manually set up `/boot` to be unencrypted and other partitions encrypted. See #1073. The **only** currently supported setup is the one I described.

**Comment by Chrysostomus** [comment]
So, it is a missing feature. Or, considering that the keyfile is always inserted, a bug actually.

**Comment by abucodonosor** [comment]
It's not a missing feature nor a bug, using unencrypted /boot is simply unsupported.

**Comment by hphilm** [comment]
@abucodonosor: I vaguely remember there was an issue or request to support unencrypted `/boot` for some reason. I understand that we currently only support full encryption, but would encryption only of `/home` not be for some use-cases enough?

**Comment by hphilm** [comment]
Seems even Ubuntu switched to **full-encryption** by now: https://mutschler.eu/linux/install-guides/ubuntu-btrfs/

**Comment by abucodonosor** [comment]
@philmmanjaro 

Sure we can switch/offer to manually unlocking, without a key stored anywhere.

But what people wanted calamares to do is to uses a key for automatic unlocking but offer unencrypted /boot
bc of 'fast boot' issues or other weird reasons. That scenario is completely insecure bc your key is stored in the initramfs,
which is stored in /boot which is then unencrypted.

**Comment by hphilm** [comment]
right, that makes no sense in that case ...

**Comment by Chrysostomus** [comment]
Obviously you wouldn't store the key in initramfs if /boot is unencrypted. From what I've seen people want 
- use keyfile in initramfs if /boot is encrypted
- don't use keyfile if only /root is encrypted

I think that's the pretty reasonable expectation of a user who mounts their /boot to esp or another unencrypted partition.

**Comment by abucodonosor** [comment]
@Chrysostomus 

You say that which is correct, but search what people really expect with unencrypted /boot :).
Discussed in a lot of issues, IRC, etc.

> I think that's the pretty reasonable expectation of a user who mounts their /boot to esp or another unencrypted partition.

Unfortunately, that is not the case. Very few people really care or understand the impact of having /boot unencrypted and a key stored there. Also, they don't like to type passwords for each crypted partition. 

Like I've said I personally don't have a problem offering LUKS without a key stored anywhere.

**Comment by Chrysostomus** [comment]
Okay. I can write a PR for supporting a unencrypted /boot without any keyfiles.

**Comment by abucodonosor** [comment]
@Chrysostomus 

sure go ahead, but keep in mind there are some scenarios you need to take care of.

For auto partitioning / replace there needs to be a GUI option too, for manually partitioning there could be a check
for /boot probably. Also, all initramfs implementations we have need adjusting as well as grub* modules etc.

**Comment by Chrysostomus** [comment]
I'm not doing anything to the autopartitioning, I think the defaults are fine as they are. Only manual partitioning needs support for this as far as I'm concerned. I¨m thinking of a simple check if boot is on unencrypted partition. If yes, don't write keyfile, don't insert it into initramfs and don't enable the password query in grub. And don¨t point to the keyfile in crypttab

**Comment by Bleuzen** [comment]
@Chrysostomus well, only because /boot is not encrypted doesn't mean a keyfile can't be used.
Maybe just the place should change. Calamares could put the keyfile on the root partition (if unencrypted /boot but encrypted root is detected).
This way, if a user has multiple enrypted partitions, for example separate / (root) and /home, they don't have to enter the password twice.
They will only unlock the root partition on system startup, where a keyfile is, which is used to decrypt /home.
In this case it would still be useful to have the keyfile. But not in initramfs, only the place has to change.

**Pull request merged**
