### PR TITLE
Suggest: Encrypt /boot

### PR DESCRIPTION
**Pull request by triceratops1**
There are some techniques for defeat encrypted volumes,   but you could defeat it with encrypt /boot.

For it i suggest an option for encrypt boot, and make a trully FDE

this is a tutorial for defeat a normal FDE

https://twopointfouristan.wordpress.com/2011/04/17/pwning-past-whole-disk-encryption/   
and a tutorial for protect you against that (modify /boot, run system and install a tricky version of cryptsetup)   

https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#Encrypted_boot_partition_.28GRUB.29

BEST REGARDS

### CODE REVIEW

**Comment by philmmanjaro** [comment]
What does this request do? This is upstream. Denied.

**Comment by teo** [comment]
@triceratops1 Please don't use pull requests for feature requests. That's what [calamares.io/bugs](https://calamares.io/bugs) is for.
Either way, Calamares already supports full disk encryption, in fact encrypted GRUB is the only recommended way to deploy Calamares with encryption support.

**Comment by kkofler** [comment]
This was just a case of somebody abusing pull requests for RFEs.

RFEs must be filed to https://calamares.io/bugs/ – no separate account needed, you can (must, in fact) log in with your GitHub credentials.

**Comment by triceratops1** [comment]
@teo  thanks    

@kkofler sorry

**Pull request closed without merging**
