### PR TITLE
grub: use uefi firmware workaround

### PR DESCRIPTION
**Pull request by codeworkx**
Source: https://wiki.archlinux.org/index.php/GRUB#UEFI_firmware_workaround

Please test before pulling!!!

### CODE REVIEW

**Comment by manjaro** [comment]
Code looks fine from my end. I can only test it within VirtualBox but not on real hardware. @demmm can you check it?

**Comment by demmm** [comment]
Sorry, not using GRUB, gummiboot is best to install from just /boot and by default installs that file then in that path.

**Comment by manjaro** [comment]
@demmm: so code-wise it is also fine for you?
@codeworkx: as it doesn't hurt anyone I'd suggest to merge your request.
@teo: any thoughts on this one?

**Comment by teo** [comment]
This is non-destructive, and disk space is cheap. I'm merging. Thanks for the patch.

**Pull request merged**
