### PR TITLE
#1935 - Reuse luks partitions

### PR DESCRIPTION
**Pull request by abalfoort**
This should fix issue #1935.

When editing an existing luks partition the user can provide the corresponding passphrase limited by the mount point chosen: custom or /home.

Adapting the existing partition objects is done in src/modules/partition/core/KPMHelpers.cpp - updateLuksDevice.

updateLuksDevice is called EditExistingPartitionDialog.cpp and when updateLuksDevice fails, a message is shown.

EncryptWidget was adapted for this change.

### CODE REVIEW

**Comment by abalfoort** [comment]
Unfortunately the branch I created for this change was not created.
Closing to try again.

**Comment by abalfoort** [comment]
I don't know how to fix this failed check:
fatal: Remote branch 1952/merge not found in upstream origin

If anyone can help me with that, please.

**Comment by adriaandegroot** [comment]
The CI failure is a problem of the CI action, not a problem of your pull request.

> For context: GitHub has a "checkout" action that does a gazillion things, and is generic, and broke when git released a security fix. That was later fixed in the GH action, but any *other* use of git in CI was still broken. So Calamares grew a really **simple** "checkout" action, but that doesn't handle branches-from-forks at all. If you want to get lost in the weeds of GH CI -- I'd suggest against it, it's just another bunch of vendor lock-in -- take a look at https://github.com/calamares/actions

**Comment by adriaandegroot** [comment]
Some retroactive comments:

- please *do* apply the common Calamares formatting tool to the source before committing. Feel free to format differently while editing, whatever is your jam, but `ci/calamaresstyle` on the sources should happen always. Now I did it after merging, so we have some ping-ponging of `KPMHelpers.cpp` which is indented and then outdented by 4 spaces.
- `int updateLuksDevice( Partition* partition, const QString& passphrase )` is missing API documentation (what does this do? in what sense "update"?), and the return value is mysterious; what does it indicate? what is success? are there different failure modes? Prefer an enum class so that we can use the compiler to help us.

**Comment by abalfoort** [comment]
Sorry about that. I will  run `ci/calamaresstyle` in the future. I had to compile clang-format 12 from source because it is not available in Debian Bullseye. For future reference:

```
git clone https://github.com/llvm/llvm-project --branch release/12.x --depth 1
cd llvm-project
mkdir build
cd build
cmake ../llvm -DCMAKE_BUILD_TYPE=Release -G"Unix Makefiles" -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=/usr/local/clang-format-12
make -j$(nproc) clang-format
sudo make install-clang-format
```
and add /usr/local/clang-format-12/bin to PATH.

I will create an enum for the return values.
How do you prefer your documentation (where can I find the documentation on that)?

**Pull request merged**
