### PR TITLE
[Proposition] Python Better Docstrings

### PR DESCRIPTION
**Pull request by Gormogon**
Proposing better in-code documentation (eventually covering C++ as well).  This takes care of most/if not all of the Python code (may have missed a few).  These are obviously not filled out yet, but it's a start.

### CODE REVIEW

**Comment by Gormogon** [comment]
You're correct about the single-line short descriptions. I will fix this.  As for the empty doctring, while I agree that empty docstrings are not good, I tried to set up docstrings EVERYWHERE there should be a docstring so that they can eventually be filled out. In other words, the ones that are currently empty are placeholders for where we need doctrings to be filled out.

Since currently the only in-code documentation seems to be a few scattered comments I figured this is a good place to start to at least get started and add consistency...

**Comment by rshipp** [comment]
This is just my opinion, but I believe it's better to leave the docstrings out unless they are being filled in with useful information. Since docstrings are necessary everywhere, leaving a placeholder doesn't seem too useful to me. 

Thanks for taking the time to look over and fix all these Python modules. :sparkles: :cake: :sparkles:

**Comment by teo** [comment]
Thanks for starting this, @Gormogon . I agree with @rshipp though that empty docstrings are less than ideal. Let's do something else: @Gormogon could you please push this to a new branch in the calamares/calamares repo? So we can fill out the docs over the next few days and merge when it's all filled out.
Would that work for everyone?

**Comment by Gormogon** [comment]
That sounds like a greate idea @teo. This is better then cluttering mater with empty docstrings.  Not sure that I have permission to push this directly to calamares/calamares, but I'll set up another branch and give it a shot.

**Comment by teo** [comment]
@Gormogon you do now.

**Pull request closed without merging**
