### PR TITLE
Fix typos in partition module files

### PR DESCRIPTION
**Pull request by isaagar**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Why do you see an typo here? Those are the marked hot keys for keyboard shortcuts to achieve tasks without using the mouse. Defined marked character made sense. By redefining those we have to see if we have a benefit gained out of it. I would NACK it for now as I don't see a need for it. Thoughts @adriaandegroot

**Comment by kkofler** [comment]
Have you checked that your changed keyboard shortcuts are non-conflicting? (There is usually a reason to not choose the first character as the shortcut.) Or do you just want a Hacktoberfest t-shirt? ;)

**Comment by isaagar** [comment]
@philmmanjaro oops, didn't know . 
@kkofler nope  :), while translating to my language they seem to be conflicting.
Should we add an extra character at end of word as hot key in bracket like "Encrypt (E)" ?

**Comment by kkofler** [comment]
Every language is responsible for setting its own non-conflicting hotkeys. You should try to use the first characters where possible, otherwise other characters in the word. Adding something like `(&E)` as you propose can be done, but only as a last resort if nothing else works in your language (and then, please add it only in your translation, the original English does not need it).

**Comment by isaagar** [comment]
@kkofler ok, got it. Thanks.

**Pull request closed without merging**
