### PR TITLE
Allow local installs with the packages module

### PR DESCRIPTION
**Pull request by rshipp**
Courtesy of @Inkane. Adds the ability to use pacman -U to install
local packages.

Note: the `local_install` option in the YAML will work for pacman only,
until someone edits `install` to support the rest.

### CODE REVIEW

**Comment by teo** [comment]
Looks ok, but I'd like you to make the key "localInstall" instead of "local_install" since that's the convention in all our conf files.

**Comment by philmmanjaro** [comment]
Fine with me ...

**Comment by rshipp** [comment]
This is waiting on @AlmAck and I to have time to test it on a real ISO.

**Comment by AlmAck** [comment]
Tested and works fine, only one thing to consider, every extra dependencies must be added to the  localInstall list

**Comment by s8321414** [comment]
So should be all fine here hmmm?

**Pull request merged**
