### PR TITLE
Support the already mounted loop fs (example in the blackPanther OS)

### PR DESCRIPTION
**Pull request by hmikihth**
.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
The new line 285 might break **Fedora** support. Please see also https://github.com/calamares/calamares/commit/ee2ed0921e0b5aa598c91096b6fe7f75d3914e64

**Comment by hmikihth** [comment]
I hope it will be ok, I check the distro in that line.

**Comment by philmmanjaro** [comment]
@hmikihth: much better. Please also remove the comment `# Modified for blackPanther OS support (www.blackpantheros.eu)` as it is not needed.

**Comment by kkofler** [comment]
@philmmanjaro:
> The new line 285 might break **Fedora** support. Please see also https://github.com/calamares/calamares/commit/ee2ed0921e0b5aa598c91096b6fe7f75d3914e64

Why would it? The code is being made more general in every step:
* original: proceed only if the file exists and is a regular file
* ee2ed0921e0b5aa598c91096b6fe7f75d3914e64: proceed only if the file exists and is not a directory (i.e., it can be a regular file or a special device file)
* 377a1c3a1705c850830abdd979a32dc4a093a782: proceed only if the file exists (i.e., it can be anything)

So the followup 062e9b764c9ee5959896f8df582d8e70863eb453 that hardcodes the distro is **not** needed and a step backwards. Please revert that commit.

For what it's worth, I wonder whether this pull request is needed at all, and whether you can't just point Calamares to some device file in `/dev/mapper` as I'm doing in the Fedora config. (The file name in Fedora is `/dev/mapper/live-base`.) But then again, allowing to use an already mounted directory can't really hurt, and I might even switch to using that in the Fedora config at some point.

**Comment by philmmanjaro** [comment]
Ok, then it is fine for me aswell to have https://github.com/calamares/calamares/commit/062e9b764c9ee5959896f8df582d8e70863eb453 reverted if your **Fedora** is working with it. Hardcoding a distro is always no the best way to do it.

**Comment by hmikihth** [comment]
Why you did not merge it?

**Comment by philmmanjaro** [comment]
@teo: what do you say. The code should be now fine. Also @kkofler reviewed it already.

**Comment by teo** [comment]
Thank you @hmikihth for the patch, and apologies for making you wait this long to merge (I hadn't noticed your last commit).

**Comment by hmikihth** [comment]
Thank you @teo

**Pull request merged**
