### PR TITLE
[partition] Finish LVM Volume Group support

### PR DESCRIPTION
**Pull request by cjlcarvalho**
Including LVM Volume Group creation GUI and fixing some problems with revert process when the user got an old VG.

[EDIT] Updating PR to include the remaining parts of LVM VG support.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Currently fails for **luks2**:

```
[ 76%] Building CXX object src/modules/shellprocess/CMakeFiles/shellprocesstest.dir/Tests.cpp.o
/src/src/modules/partition/core/PartitionCoreModule.cpp: In member function 'void PartitionCoreModule::scanForLVMPVs()':
/src/src/modules/partition/core/PartitionCoreModule.cpp:622:105: error: 'Luks2' is not a member of 'FileSystem::Type'
                 else if ( p->fileSystem().type() == FileSystem::Type::Luks || p->fileSystem().type() == FileSystem::Type::Luks2 )
                                                                                                         ^
src/modules/partition/CMakeFiles/calamares_viewmodule_partition.dir/build.make:238: recipe for target 'src/modules/partition/CMakeFiles/calamares_viewmodule_partition.dir/core/PartitionCoreModule.cpp.o' failed
make[2]: *** [src/modules/partition/CMakeFiles/calamares_viewmodule_partition.dir/core/PartitionCoreModule.cpp.o] Error 1
CMakeFiles/Makefile2:1688: recipe for target 'src/modules/partition/CMakeFiles/calamares_viewmodule_partition.dir/all' failed
make[1]: *** [src/modules/partition/CMakeFiles/calamares_viewmodule_partition.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by kkofler** [comment]
I guess your KPMcore is too old.

**Comment by cjlcarvalho** [comment]
@philmmanjaro Luks2 is already available in FileSystem::Type enum (at least on kpmcore's master branch).

**Comment by adriaandegroot** [comment]
This may need some #ifdeffery to make it build with released versions of KPMCore and current Calamares. It's a tricky set of dependencies, but it is needed (eventually we'll bump KPMCore version requirements).

**Comment by cjlcarvalho** [comment]
@adriaandegroot I've made a new commit to only check FileSystem::Type::Luks2 when kpmcore's version is greater than 3.3

**Comment by cjlcarvalho** [comment]
Updating PR to include the remaining parts of LVM VG support. The last commit includes the process of LVM VG resize, deactivate and remove.

**Comment by adriaandegroot** [comment]
Merged into update-lvm-support branch (off master) for testing.

**Pull request merged**
