### PR TITLE
Add support for performing operations on LVM logical volumes.

### PR DESCRIPTION
**Pull request by stikonas**
At the moment there is no UI to obtain LVM LV name, so it is hardcoded to rootfs

### CODE REVIEW

**Comment by stikonas** [comment]
Unfortunately, right now there is no GUI to obtain LV partition name. So I just added rootfs for testing.

**Comment by stikonas** [comment]
Something similar is required for other jobs as well: ResizePartitionJob, DeletePartitionJob

**Comment by adriaandegroot** [comment]
Can we complete this, clean it up, and have something that isn't just for testing before merging it?

**Comment by stikonas** [comment]
Fixed LVM LV naming issue. But this will need some other changes in kpmcore (or calamares). KPMcore has protected access to some partition functions (in particular setPartitionPath). And since Calamares uses it's own jobs, we don't have access to setPartitionPath.

**Comment by stikonas** [comment]
This will need kpmcore 3.3. Then it will compile

**Comment by adriaandegroot** [comment]
We'll just have to remember that kpmcore 3.2 branch in Calamares is for kpmcore 3.3, and not merge this yet.

**Pull request merged**
