### PR TITLE
Prevent data destruction

### PR DESCRIPTION
**Pull request by aliveafter1000**
https://github.com/calamares/calamares/issues/1044

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@adriaandegroot: what do you think about this PR? For me it looks merge-able ...

**Comment by adriaandegroot** [comment]
- needs better commit message
 - contains a bunch of churn
 - the actual effective change is adding `-o ro,noload` ... **that** seems sensible, I think

**Comment by philmmanjaro** [comment]
@adriaandegroot: I still have to test [my approach](https://gitlab.manjaro.org/applications/calamares/compare/4c73fc0...7c6ff1a3). @stikonas: do you think it is needed or does the current code we have now in **master** work already and therefore prevent data loss?

**Comment by aliveafter1000** [comment]
The current code you have now mounts peoples shit into tmp.
Lotta scripts that run could destroy it. Just because QTemporaryDir doesn't destroy it doesn't mean something else can't. You only need to read the fstab.

**Comment by adriaandegroot** [comment]
This is in-progress in the fix-partitioning branch.

**Pull request closed without merging**
