### PR TITLE
Fixed pep8 whining in module machineid

### PR DESCRIPTION
**Pull request by agaida**
added myself to copyright

### CODE REVIEW

**Comment by shadeslayer** [comment]
Perhaps a better idea would be to join strings together instead of using formatting ?

So :

A = B + "foo"

**Comment by agaida** [comment]
to be honest:
```
    target_systemd_machineid_file = root_mount_point + "/etc/machine-id"
    target_dbus_machineid_file = root_mount_point + "/var/lib/dbus/machine-id"
```
looks better to me

**Comment by shadeslayer** [comment]
That's what I'm proposing ;)

**Comment by agaida** [comment]
but it simply works and is not geeky :P

**Comment by shadeslayer** [comment]
LGTM

**Pull request merged**
