### PR TITLE
Wip/packaging flatpak

### PR DESCRIPTION
**Pull request by nintyfan**
This MR is created to work on flatpak integration. 

Not each feature related to: https://github.com/calamares/calamares/issues/1082 will be addressed. This branch aim only to provide a way to install applications from network, which are not installed on LiveCD/LiveUSB (cause these got copied by root copy mechanism).

Other features, like installing only selected packages without distro installation will be addressed by other MR.

### CODE REVIEW

**Comment by nintyfan** [comment]
Currently only shown list of flatpaks inside configured repo.
Do not blame me. I am beginner at developing software. I do not read coding style, etc. yet, but try to match my style your rules.

**Comment by dalto8** [comment]
If we want to add support for flatpak, I think it would be better to add a proper backend for it to the packages module instead of hacking it in like that.  Look at the backends for the other package managers and add it in a similar way.

Could you describe what you are trying to do with the packagechooser module?

> I do not read coding style, etc. yet, but try to match my style your rules.

You need to run clang-format against all the files you changed to apply the proper Calamares formatting.

**Comment by nintyfan** [comment]
About backends. I look inside package(s?) module. It contains python code with classes for different package manager. Problem is: list of packages in packagechooser is currently read from configuration.

**Comment by dalto8** [comment]
> About backends. I look inside package(s?) module. It contains python code with classes for different package manager. Problem is: list of packages in packagechooser is currently read from configuration.

It combines that list with one from global storage.  Prior modules can add package operations.

https://github.com/calamares/calamares/blob/calamares/src/modules/packages/main.py#L742-L743

**Comment by nintyfan** [comment]
So... I would wrote two new module. One for UI of flatpak package manager and next for fill it (list) with packages.

**Comment by dalto8** [comment]
I think you should start with an explanation of what you are hoping to accomplish.  What we understand that, we can maybe propose a methodology.

**Comment by nintyfan** [comment]
I need to accomplish:
Give a user a way to select packages to install from remote repository and made Calamares install it after/while installing system

In future:
1. Select packages to not copy from installation media or to remove it just after installation
2. (if possible) add possibility to install packages from removable media (with distribution) to installed distribution for cases with internet problems (poor countries).
By writing packages I mean flatpak packages.

**Comment by dalto8** [comment]
For example, you want someone to be able browse something like flathub and pick which flatpaks to install?

Are you also allowing them to choose normal packages to install or only flatpaks?

**Comment by nintyfan** [comment]
Only flatpaks.

**Comment by dalto8** [comment]
In that case, I would use the netinstall module.  It is better for browsing a large list of packages.

The netinstall module can already read a list from a global storage variable.  It then feeds the packages module.

Here is what I would do:
* Add support for a flatpak backend in the packages module and create a PR for that
* Create a module that reads your flatpak repo and puts the list of packages into global storage in the appropriate format
  * You can see how this is done if you look at the netinstall-add logic in the packagechooser module

From there it should just all work.  Your module will load the data for netinstall, netinstall will display to the user.  The user makes the selections and then the packages module will install them.

**Comment by nintyfan** [comment]
Thanks, but...
What about making support for multiple backends. Should I ran multiple instances of netinstall/flatpakfiller?
I see netinstall download some yml file. I see I should use local config and put each package into configuration.

**Comment by dalto8** [comment]
Superseded by #2176

**Pull request closed without merging**
