### PR TITLE
calamares_explain_skipped_modules <- wrong _calamares_add_module_subdirectory_impl

### PR DESCRIPTION
**Pull request by ghost**
[Related]
cmake: Change Release build from -O4 to -O3
https://github.com/calamares/calamares/pull/2115
Move welcome settings out of branding
https://github.com/calamares/calamares/issues/1384
settings.conf installed in strange place
https://github.com/calamares/calamares/issues/2075
Translation string seems to be missing on the about button on the side navigation
https://github.com/calamares/calamares/issues/2030

### CODE REVIEW

**Comment by dalto8** [comment]
41,000 added lines of code seems like a lot for explaining the skipped modules.

It looks like there may be an issue with the branch you are trying to merge.

**Comment by ghost** [comment]
On CMakeModules/CalamaresAddModuleSubdirectory.cmake : Some function can improve...

**Comment by adriaandegroot** [comment]
This gets a "no" because it's **huge** with many files edited for no reason, a giant addition to `.gitignore` for nonsensical files, and the description does not say what the PR is supposed to do. If you want to fix a specific issue, please file a PR that says "fixes <the issue>" where the changes obviously apply to that issue.

**Comment by adriaandegroot** [comment]
> On CMakeModules/CalamaresAddModuleSubdirectory.cmake : Some function can improve...

In that case, please file a PR that says "Functions in `CalamaresAddModuleSubdirectory.cmake` can be improved", describing for each function you are improving what the function is and how you are improving it. Or, if you do not have a PR, file an issue explaining what can be improved in the function.

**Pull request closed without merging**
